version: '3.8'

# Production configuration with automatic scheduling
services:
  market-research-agent:
    build: .
    image: market-research-agent:latest
    container_name: market-research-agent
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - FROM_EMAIL=${FROM_EMAIL}
      - TO_EMAIL=${TO_EMAIL}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN:-}
      - SLACK_CHANNEL=${SLACK_CHANNEL:-}
      - TZ=America/New_York
    volumes:
      - market-reports:/app/reports
    restart: "no"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  scheduler:
    image: mcuadros/ofelia:latest
    container_name: market-research-scheduler
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./scheduler-config.ini:/etc/ofelia/config.ini:ro
      - market-reports:/app/reports
    restart: always
    depends_on:
      - market-research-agent

volumes:
  market-reports:
    driver: local