version: '3.8'

services:
  market-research-agent:
    build: .
    container_name: market-research-agent
    environment:
      # Groq API Configuration
      - GROQ_API_KEY=${GROQ_API_KEY}
      
      # Email Configuration
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - FROM_EMAIL=${FROM_EMAIL}
      - TO_EMAIL=${TO_EMAIL}
      
      # Slack Configuration (optional)
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN:-}
      - SLACK_CHANNEL=${SLACK_CHANNEL:-}
      
      # Timezone
      - TZ=America/New_York
    
    volumes:
      # Mount reports directory to persist reports
      - ./reports:/app/reports
      
      # Mount .env file if you prefer file-based config
      - ./.env:/app/.env:ro
    
    # Restart policy for production
    restart: "no"
    
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  # Optional: Run on schedule using ofelia
  scheduler:
    image: mcuadros/ofelia:latest
    container_name: market-research-scheduler
    depends_on:
      - market-research-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./scheduler-config.ini:/etc/ofelia/config.ini:ro
    restart: unless-stopped